import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 加载 Google 字体并将变量注入到全局 class 中，便于 Tailwind 或自定义样式使用
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 页面元数据（Next.js App Router 支持）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根布局组件：包裹所有页面内容并注入字体变量与全局样式
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
